/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AlphaToken__factory } from "./AlphaToken__factory";
export { Spaceships__factory } from "./Spaceships__factory";
