<?php

/**
 * Stripe Payment Gateway.
 *
 * @link    https://pluginsware.com
 * @since   1.6.4
 *
 * @package Advanced_Classifieds_And_Directory_Pro
 */
 
// Exit if accessed directly
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * ACADP_Premium_Public_Stripe class.
 *
 * @since 1.6.4
 */
class ACADP_Premium_Public_Stripe {

	/**
	 * Register stripe specific styles & scripts.
	 *
	 * @since 1.6.4
	 */
	public function register_styles_scripts() {
		
	}
	
	/**
	 * Enqueues stripe specific styles & scripts.
	 *
	 * @since 1.6.4
	 */
	public function enqueue_styles_scripts() {
		wp_enqueue_script( 'jquery' );
		wp_enqueue_script( ACADP_PLUGIN_NAME . '-premium-public-stripe' );
		wp_enqueue_script( ACADP_PLUGIN_NAME . '-premium-public-stripe-processing' );	
	}
	
	/**
	 * Display a credit card form for Stripe.
	 *
	 * @since 1.6.4
	 */
	public function cc_form() {	
		ob_start();
		?>        
        <div id="acadp-cc-form-stripe" class="panel panel-default">
        	<div class="panel-heading"><?php _e( 'Enter your card details', 'advanced-classifieds-and-directory-pro' ); ?></div>
            
            <div class="panel-body">
            	<div class="row">
                	<div class="col-md-9 col-xs-12">
        				<div class="form-group">
      						<label class="control-label" for="acadp-card-number"><?php _e( 'Card Number', 'advanced-classifieds-and-directory-pro' ); ?><span class="acadp-star">*</span></label>
                			<input type="text" autocomplete="off" id="acadp-card-number" class="form-control" placeholder="<?php _e( 'Card number', 'advanced-classifieds-and-directory-pro' ); ?>" />
    					</div>
                	</div>
            
            		<div class="col-md-3 col-xs-12">
            			<div class="form-group">
      						<label class="control-label" for="acadp-card-cvc"><?php _e( 'CVC', 'advanced-classifieds-and-directory-pro' ); ?><span class="acadp-star">*</span></label>
                			<input type="text" autocomplete="off" id="acadp-card-cvc" class="form-control" placeholder="<?php _e( 'CVC', 'advanced-classifieds-and-directory-pro' ); ?>" />
    					</div>
                	</div>
                </div>
            
            	<div class="form-group">
            		<label class="control-label"><?php _e( 'Expiry Date', 'advanced-classifieds-and-directory-pro' ); ?><span class="acadp-star">*</span></label>
            		<div class="row">
                		<div class="col-md-6 col-xs-6">
                			<input type="text" id="acadp-card-expiry-month" class="form-control" placeholder="<?php _e( 'MM', 'advanced-classifieds-and-directory-pro' ); ?>" />
                		</div>
                    	<div class="col-md-6 col-xs-6">
                			<input type="text" id="acadp-card-expiry-year" class="form-control" placeholder="<?php _e( 'YYYY', 'advanced-classifieds-and-directory-pro' ); ?>" />
                    	</div>
                	</div>
    			</div>
            </div>
        </div>             
        <?php
		echo ob_get_clean();
		wp_die();		
	}
	
	/**
	 * Process Stripe Payment.
	 *
	 * @since 1.6.4
	 * @param int   $order_id Order ID.
	 */
	public function process_payment( $order_id ) {	
		$gateway_settings  = get_option( 'acadp_gateway_settings' );
		$stripe_settings   = get_option( 'acadp_gateway_stripe_settings' );
		
		$currency          = acadp_get_payment_currency();	
		$secret_key        = empty( $gateway_settings['test_mode'] ) ? $stripe_settings['live_secret_key'] : $stripe_settings['test_secret_key'];
		$amount            = get_post_meta( $order_id, 'amount', true );
		$error             = '';

		// Retrieve the token generated by stripe.js
		if ( isset( $_POST['stripe_token'] ) ) {		
			$token = $_POST['stripe_token'];

			// Load the stripe libraries
			require_once ACADP_PLUGIN_DIR . 'premium/vendor/stripe/init.php';
		
			// Attempt to charge the customer's card
			try {		
				\Stripe\Stripe::setApiKey( $secret_key );
			
				$charge = \Stripe\Charge::create( array(
						'amount'      => $amount * 100,
						'currency'    => $currency,
						'source'      => $token,
						'description' => $order_id
					)
				); 
				
				if ( $charge->paid == true ) {			
					acadp_order_completed( array( 'id' => $order_id, 'transaction_id' => $charge->id ) );				
				} 
			} catch( \Stripe\Error\Card $e ) {
    			$body = $e->getJsonBody();
				$error = __( $body['error']['message'], 'advanced-classifieds-and-directory-pro' );				
			} catch ( \Stripe\Error\InvalidRequest $e ) {
				$error = __( "Invalid parameters supplied to Stripe's API", 'advanced-classifieds-and-directory-pro' );				
			} catch ( \Stripe\Error\Authentication $e ) {
				$error = __( "Authentication with Stripe's API failed. Maybe you changed API keys recently", 'advanced-classifieds-and-directory-pro' );				
			} catch ( \Stripe\Error\Api $e ) {
				$error = __( "Stripe's servers are down!", 'advanced-classifieds-and-directory-pro' );				
			} catch ( \Stripe\Error\ApiConnection $e ) {			
    			$error = __( "Network problem, perhaps try again.", 'advanced-classifieds-and-directory-pro' );				
			} catch ( \Stripe\Error\Base $e ) {			
				$error = __( "Sorry, something went wrong.", 'advanced-classifieds-and-directory-pro' );				
			} catch ( Exception $e ) {
				$error = __( "Sorry, something went wrong. Completely unrelated to Stripe", 'advanced-classifieds-and-directory-pro' );				
			}		
		} else {		
			$error = __( 'The order cannot be processed. You have not been charged. Please confirm that you have JavaScript enabled and try again.', 'advanced-classifieds-and-directory-pro' );			
		}
		
		// Redirect
		if ( '' == $error ) {
			$redirect = acadp_get_payment_receipt_page_link( $order_id );				
		} else {		
			$redirect = acadp_get_failure_page_link( $order_id );
			
			// Set error message in WP transient
			set_transient( "acadp_payment_errors_{$order_id}", $error, 30 );			
		}

		wp_redirect( $redirect );	
		exit;		
	}

}
